//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alquiler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Alquiler()
        {
            this.DetalleParticipante = new HashSet<DetalleParticipante>();
        }
    
        public int CAlquiler { get; set; }
        public int CEquipo { get; set; }
        public int CCancha { get; set; }
        public System.DateTime DFechaInicio { get; set; }
        public int NumHoras { get; set; }
        public decimal MDescuento { get; set; }
        public decimal MTotal { get; set; }
        public bool FPagado { get; set; }
    
        public virtual Cancha Cancha { get; set; }
        public virtual Equipo Equipo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleParticipante> DetalleParticipante { get; set; }
    }
}
