//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cancha
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cancha()
        {
            this.Alquiler = new HashSet<Alquiler>();
        }
    
        public int CCancha { get; set; }
        public int CPropietario { get; set; }
        public int CCalle { get; set; }
        public string NCancha { get; set; }
        public string TDireccion { get; set; }
        public decimal MPrecioHora { get; set; }
        public byte[] ImgFoto1 { get; set; }
        public byte[] ImgFoto2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alquiler> Alquiler { get; set; }
        public virtual Calle Calle { get; set; }
        public virtual Propietario Propietario { get; set; }
    }
}
