//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleParticipante
    {
        public int CDetalleParticipante { get; set; }
        public int CAlquiler { get; set; }
        public int CParticipante { get; set; }
        public decimal MCuota { get; set; }
        public bool FPartePagada { get; set; }
        public int NCupos { get; set; }
    
        public virtual Alquiler Alquiler { get; set; }
        public virtual Participante Participante { get; set; }
    }
}
