//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int CUsuario { get; set; }
        public long CDNI { get; set; }
        public string NUsuario { get; set; }
        public long NumTelefono { get; set; }
        public string usuario1 { get; set; }
        public string pswd { get; set; }
        public byte[] ImgFoto { get; set; }
    
        public virtual Jugador Jugador { get; set; }
        public virtual Propietario Propietario { get; set; }
    }
}
